# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cudi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cudi

  target 'CudiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CudiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod "MediaWatermark"
  pod "SwiftyCam"
  
end
